### ISSUE TITLE
预训练权重加载问题

### ISSUE THREAD

**Issue by GrandMountFoxc** [Jun-Jie-Shi/M2FTrans#1]
您好，请问GitHub上提供的预训练权重应该怎么加载，直接加载会出错，会存在参数不匹配的问题。不清楚是不是我哪里设置的不对，麻烦您有时间看一下。
![image](https://github.com/Jun-Jie-Shi/M2FTrans/assets/97771413/34747cb1-597b-455f-baae-fd05534a400b)
![image](https://github.com/Jun-Jie-Shi/M2FTrans/assets/97771413/7bf5ff6e-1a02-4e79-8b71-87a3b472b5fb)

**Comment by Jun-Jie-Shi** [comment]
@GrandMountFoxc 看上去您使用的模型的basic_dims应该是8，但给予的预训练权重的basic_dim应该为16；另外所给模型的输入3D裁剪大小为80*80*80，您好像改成了128*128*128，从而导致了该报错。

**Comment by GrandMountFoxc** [comment]
好的，感谢回复
