### ISSUE TITLE
txt文件

### ISSUE THREAD

**Issue by 1707001010** [Jun-Jie-Shi/M2FTrans#2]
你好，能提供一下BraTS2018和2020数据划分的txt文件吗

**Comment by Jun-Jie-Shi** [comment]
@1707001010 您好，您可以在文件目录[BraTS](https://github.com/Jun-Jie-Shi/M2FTrans/tree/main/BraTS)下找到对应的txt文件。

**Comment by 1707001010** [comment]
> @1707001010 您好，您可以在文件目录[BraTS](https://github.com/Jun-Jie-Shi/M2FTrans/tree/main/BraTS)下找到对应的txt文件。感谢大佬
