### ISSUE TITLE
对于val验证数据集的一个小疑惑

### ISSUE THREAD

**Issue by WDYTX** [Jun-Jie-Shi/M2FTrans#3]
您好，我想问下是否使用了验证集（也就是val.txt）文件所指的那些数据？文章里的结果是用验证集得到的结果还是测试集得到的结果呢？感谢！！！

**Comment by WDYTX** [comment]
好像验证集没有用上啊

**Comment by Jun-Jie-Shi** [comment]
@WDYTX 您好，这里验证集的划分是为了保证与先前工作的一致性，文章的结果是用测试集得到的，当然我们也尝试了选择部分缺失情况在训练过程中进行验证(在train函数中被注释掉了)，但观察到模型1000轮次的结果似乎也尚未达到完全收敛，因此简单起见就直接选取了最后一轮的测试结果。

**Comment by WDYTX** [comment]
好的，非常感谢您的回复！！！

**Comment by WDYTX** [comment]
您好，我想问一下这个模型训练需要训练多久啊？

**Comment by Jun-Jie-Shi** [comment]
@WDYTX 如果设置iter_per_epoch=150的话，跑1k轮大约51 h，如果设置为每轮遍历整个数据集的话就得视数据集大小以及总轮次而变化了
