### ISSUE TITLE
P值

### ISSUE THREAD

**Issue by diaoyq121** [Jun-Jie-Shi/M2FTrans#4]
您好，想问一下作者，P值是怎么计算的？

**Comment by Jun-Jie-Shi** [comment]
@1707001010 您好，由于是在缺失模态场景下，我们采取了对15种多模态设置下的平均分数进行计算P值。具体而言，我们统计并计算每个样本在15种多模态设置下的平均测试分数(DSC或HD95)，然后将提出的方法与过去不同模型方法得到的分数进行配对样本T检验(我们直接使用了excel工具中的T-Test函数进行计算)， 从而得我们方法与过去方法之间的P值，希望能对你有帮助。
